import Head from "next/head";
import Blogcard from "../components/Blogbox";
import fs from "fs";
import matter from "gray-matter";

export default function Home(props) {
  const { posts } = props;
  return (
    <div>
      <Head>
        <title>PrtmTechie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {posts.map((post, index) => (
        <Blogcard key={index} post={post} />
      ))}
    </div>
  );
}

export async function getStaticProps() {
  const files = fs.readdirSync("posts");

  const posts = files.map((file) => {
    const slug = file.replace(".md", "");

    const filecontent = fs.readFileSync(`posts/${file}`, "utf-8");
    const parsedContent = matter(filecontent);
    const { data } = parsedContent;

    return {
      slug,
      data,
    };
  });

  return {
    props: {
      posts,
    },
  };
}
